### ISSUE TITLE
Metagrammar for SINGLE_QUOTED_CHAR

### ISSUE THREAD

**Issue by psfblair** [lukehutch/pikaparser#13]
I see this in MetaGrammar.java:

```java
            // Single quoted character
            rule(SINGLE_QUOTED_CHAR, //
                    first( //
                            ruleRef(ESCAPED_CTRL_CHAR), //
                            c('\'', '"').invert())), // TODO: replace invert() with NotFollowedBy
```

The ESCAPED_CTRL_CHAR takes care of allowing escaped quotes. The following clause indicates that any character that is not a backslash or a double-quote is accepted. Shouldn't that be a single quote in there rather than a double quote?

Also, is there a need to replace invert() with NotFollowedBy if this is for single quoted characters? The rule only allows for a single non-backslash-or-quote character, or one of the specified escape sequences. Doesn't that cover all the bases?

**Comment by lukehutch** [comment]
That's not a backslash -- `'\''` is a single quote character, quoted and escaped.

However, you're right, the `'"'` can be removed... I think that's left over from when I had single-quoted chars and double-quoted strings use the same character escaping scheme (which was not correct)...

Replacing `.invert()` by `NotFollowedBy` doesn't change the logic, but it's more efficient, because `.invert()` creates way more terminal matches (one at almost every character position), whereas `NotFollowedBy` is only triggered top-down when needed (in `MemoTable.lookUpMatch`)

**Comment by lukehutch** [comment]
Fixed in git master

**Comment by psfblair** [comment]
I see; it's so easy to get confused with these escape characters!
