### ISSUE TITLE
Move to Kotlin?

### ISSUE THREAD

**Issue by psfblair** [lukehutch/pikaparser#16]
I've created a release (https://github.com/psfblair/pikaparser-kotlin/releases/tag/pikaparser-0.0.1-SNAPSHOT-equivalent), which based on the tests has feature- and performance-parity with the current Java version. If you'd be interested in developing the reference implementation in Kotlin in the future, feel free to pull it into your repository; you'd just need to change the copyright and the package names back to yours. A few files and methods did get moved around, so depending on how committed you are to your existing organization, you might want to move them back. 

From this point I intend to do a lot of refactoring and reorganization, primarily so that I can understand much better the details of the code, and then start modifying the implementation to the extent that I need to do so for my plans. So I think this release would be the point you'd want to branch from, if it's of interest.

**Comment by lukehutch** [comment]
Thanks, I appreciate this. I do want to use Kotlin when I ramp up work on my language, so this is probably a good starting point (though that is on hold right now as I have other projects going on).

I will probably leave the reference parser in Java though, since the paper covering the parser is now in peer review, and I think it's better to use Java for the reference, since it is more widely used than Kotlin.
