### ISSUE TITLE
Support for out-of-source builds

### ISSUE THREAD

**Issue by elfring** [lukehutch/pikaparser#22]
[The file “pom.xml”](https://github.com/lukehutch/pikaparser/blob/1bdcb3d8c6a2d8074e5b486c0794c0fd1f927375/pom.xml#L1 "Build specification") is used for software build management by the tool “Maven”.
:thinking: I would generally appreciate if [generated files will be separately stored from the source directory](https://stackoverflow.com/questions/14117709/configuring-maven-to-generate-output-outside-the-project-directory "Configuring Maven to generate output outside the project directory").
Thus I suggest to specify [output directories](https://maven.apache.org/pom.html#the-build-element-set "Configuration for directories") accordingly.

**Comment by lukehutch** [comment]
Did you test this? Source codes are in `src/`, and generated files are placed in a new directory `target/` when you run `mvn package`.

**Comment by elfring** [comment]
I would prefer to [choose a target directory](https://maven.apache.org/pom.html#the-basebuild-element-set "Description for BaseBuild settings") which is separate from the source hierarchy.
Do you imagine that such a build configuration would be selected only under special circumstances?

**Comment by lukehutch** [comment]
You are of course welcome to modify `pom.xml` if you want, but it already uses the Maven defaults that completely separate the source directory from the target directory:

```
projectdir/
    - src/
    - target/
    - pom.xml
```

Literally almost 100% of Maven projects do this. It is standard.

If you want `target/` to not even be in `projectdir/`, then yes, you can override it. But there is no reason to do it in the `pom.xml` that is shipped with the project, because the above works for almost all usecases and almost all users.

Note that you can simply delete `target/` and all generated files are gone. There is no mixing of generated files with source files.

If you want to be able to override the target directory from the commandline, you could follow one of these suggestions to set up a profile or commandline parameter that specifies the build directory:

https://stackoverflow.com/questions/3908013/maven-how-to-change-path-to-target-directory-from-command-line

**Comment by elfring** [comment]
Thanks for your link to additional build configuration options.
