### ISSUE TITLE
Support for character classes

### ISSUE THREAD

**Issue by elfring** [lukehutch/pikaparser#25]
I have noticed that the code “`[a-z]`” is used within [the file “arithmetic.grammar”](https://github.com/lukehutch/pikaparser/blob/3f3e042e43cbd5052b8e31681ff6e3048d9e1cbf/README.md#grammar-description-file-arithmeticgrammar "Grammar file example").
I miss a corresponding description. (I would interpret it as a search pattern for a character range in the way I am used to from the application of regular expressions.)
:bulb: Would you like to [support character classes](https://en.wikipedia.org/wiki/Regular_expression#Character_classes "Description for usage of character classes")?

By the way:
How do you think about to make the example and explanations separately linkable?

**Comment by lukehutch** [comment]
Yes, they're supposed to work as character classes (or more specifically, character ranges). They implement the most widely-used subset of regexp character classes (including inversion, ranges, escaping, and individual characters). They should already work (I have used them a lot), so if anything doesn't work, it's a bug, and you should file a bug report specifically for the thing that doesn't work. If you need other types of character class special characters than what is supported, please submit a pull request, or a feature request if it's something you need and want to actively use (rather than just a theoretical "nice to have" feature). Thanks!

**Comment by elfring** [comment]
Would you like to adjust the provided software documentation accordingly?

**Comment by lukehutch** [comment]
I updated the `README.md` file to include info on character classes. You're right, that needed to be documented. However, note that `README.md` is just a standard file in the repo like everything else, so if you have  suggestions like this on updating the documentation, a pull request would be greatly appreciated. Thanks!
