### ISSUE TITLE
Extend exception class hierarchy

### ISSUE THREAD

**Issue by elfring** [lukehutch/pikaparser#28]
[An exception like “IllegalArgumentException” is thrown](https://github.com/lukehutch/pikaparser/search?q=IllegalArgumentException "Usage of selected exception objects") at some source code places.
:thinking: I find its usage occasionally questionable.
:bulb: Thus I suggest to [add more appropriate exception classes](https://docs.oracle.com/javase/tutorial/essential/exceptions/creating.html "Creating exception classes").

**Comment by lukehutch** [comment]
`IllegalArgumentException` is the correct exception to throw in almost every one of those cases, since it literally means "one or more of the argument values that you passed into this function were wrong or inappropriate in some way", and that's exactly what almost all of those examples you linked are complaining about. Sure, you can create a huge rich hierarchy of exceptions, but there's really no point in doing that, especially for *unchecked* exceptions like these ones, since ultimately every unchecked exception is a subclass of `RuntimeException`, so anyone who wants to catch unexpected occurrences like this has to catch `RuntimeException` to catch all of them (i.e. the actual subclass doesn't even matter). (`IllegalArgumentException` subclasses `RuntimeException`.)

Only one or two of the examples you linked were for things not strictly related to arguments, e.g. methods that were illegal to call on a given class in the class hierarchy or similar, but it's not worth introducing a whole new type of exception for just one or two sanity check cases whose exception will almost never be thrown, unless the calling code is doing something really wrong.

**Comment by elfring** [comment]
>Sure, you can create a huge rich hierarchy of exceptions,

I propose to take further software design possibilities into account.


>but there's really no point in doing that, …

I got additional development ideas.


>…, so anyone who wants to catch unexpected occurrences like this has to catch `RuntimeException` to catch all of them …

How do you think about to distinguish parsing errors in more detail?


>Only one or two of the examples you linked were for things not strictly related to arguments, …

Can such an implementation detail become more interesting?


>…, but it's not worth introducing a whole new type of exception for just one or two sanity check cases …

I imagine that dedicated data structures can be more helpful for better case distinctions


>…, unless the calling code is doing something really wrong.

and corresponding error handling.

**Comment by lukehutch** [comment]
On Thu, Oct 8, 2020 at 5:21 AM Markus Elfring <notifications@github.com>
wrote:

> …, so anyone who wants to catch unexpected occurrences like this has to
> catch RuntimeException to catch all of them …
>
> How do you think about to distinguish parsing errors in more detail?
>
You have to write the code that handles parsing errors (and "distinguishes
them") however is appropriate for your application.

> Only one or two of the examples you linked were for things not strictly
> related to arguments, …
>
> Can such an implementation detail become more interesting?
>
Sorry, I don't understand the question.

> …, but it's not worth introducing a whole new type of exception for just
> one or two sanity check cases …
>
> I imagine that dedicated data structures can be more helpful for better
> case distinctions
>
You have to take the context into account. If you're reporting an error
that is fatal no matter what, and/or if you don't want the caller to have
to set up a lot of exotic try/catch clauses to catch every possible
contingency (especially when almost all of the exceptions you pointed out
should never actually be thrown under normal usage), then you do it the way
I already did it in the code. There is no point creating custom exceptions
for exceptions that literally mean "you called this method wrong". If
another piece of software wants to catch the exceptions thrown by pika
parser, they can just catch RuntimeException.

If you want to create your own exceptions for these special cases, you are
welcome to fork the code and do so.
